image: ubuntu
services:
- docker
branches:
  only:
    - master
install:
  - git submodule update --init --recursive
  - nuget restore Server.sln
build_script:
  - dotnet publish Server.sln -c Release
  - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASSWORD"
  - ps: docker build -t hub.docker.com/r/burningblaze/pmdshiftserver:latest .
  - ps: docker push hub.docker.com/r/burningblaze/pmdshiftserver:latest